version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: mever_postgres
    environment:
      POSTGRES_USER: mever
      POSTGRES_PASSWORD: mever1234
      POSTGRES_DB: mever_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: mever_redis
    command: redis-server --requirepass mever_redis_pass
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: mever_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: mever_access
      MINIO_ROOT_PASSWORD: mever_secret
    ports:
      - "9000:9000" # API
      - "9001:9001" # Web Console
    volumes:
      - minio_data:/data

  nginx-vod:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: mever_nginx_vod
    ports:
      - "8080:80" # Akses dari Windows: http://localhost:8080
    volumes:
      # Mount nginx.conf agar bisa edit tanpa rebuild image
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - minio
    # Agar Nginx bisa memanggil Backend yang jalan di host WSL
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data:
